{
 "title": "Fission dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of function calls",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fission_function_calls_total" }
   ]
  },
  {
   "title": "Total time of function running (s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "fission_function_duration_seconds_sum",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Function duration (quantile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fission_function_duration_seconds",
     "legendFormat": "{{path}} q:{{quantile}} {{cached}}"
    }
   ]
  },
  {
   "title": "Function overhead seconds summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "fission_cold_starts_total" }
   ]
  }
 ]
}